CREATE TABLE providers(
    id SERIAL PRIMARY KEY,
    name VARCHAR,
    url VARCHAR
);

CREATE TABLE tickers(
    providers_id INTEGER REFERENCES providers,
    permaticker NUMERIC UNIQUE,
    ticker VARCHAR UNIQUE,
    name VARCHAR,
    exchange VARCHAR,
    isdelisted BOOLEAN,
    category VARCHAR,
    cusips VARCHAR,
    siccode NUMERIC,
    sicsector VARCHAR,
    sicindustry VARCHAR,
    famasector VARCHAR,
    famaindustry VARCHAR,
    sector VARCHAR,
    industry VARCHAR,
    scalemarketcap VARCHAR,
    scalerevenue VARCHAR,
    relatedtickers VARCHAR,
    currency VARCHAR,
    location VARCHAR,
    lastupdated DATE,
    firstadded DATE,
    firstpricedate DATE,
    lastpricedate DATE,
    firstquarter DATE,
    lastquarter DATE,
    secfilings VARCHAR,
    companysite VARCHAR,
    PRIMARY KEY (permaticker, ticker)
)

CREATE TABLE prices(
    providers_id INTEGER REFERENCES providers,
    ticker VARCHAR REFERENCES tickers(ticker),
    table_id VARCHAR CHECK (table_id = 'SEP' OR table_id = 'SFP'),
    date TIMESTAMP,
    frequency VARCHAR CHECK (frequency = 'DAILY' OR frequency = 'MINUTE'),
    open NUMERIC,
    high NUMERIC,
    low NUMERIC,
    close NUMERIC,
    volume NUMERIC,
    closeadj NUMERIC,
    closeunadj NUMERIC,
    lastupdated DATE,
    PRIMARY KEY (ticker, date, frequency)
);

CREATE TABLE fundamentals(
    providers_id INTEGER REFERENCES providers,
    ticker VARCHAR REFERENCES tickers(ticker),
    dimension VARCHAR,
    calendardate DATE,
    datekey DATE,
    reportperiod DATE,
    lastupdated DATE,
    accoci NUMERIC,
    assets NUMERIC,
    assetsavg NUMERIC,
    assetsc NUMERIC,
    assetsnc NUMERIC,
    assetturnover NUMERIC,
    bvps NUMERIC,
    capex NUMERIC,
    cashneq NUMERIC,
    cashnequsd NUMERIC,
    cor NUMERIC,
    consolinc NUMERIC,
    currentratio NUMERIC,
    de NUMERIC,
    debt NUMERIC,
    debtc NUMERIC,
    debtnc NUMERIC,
    debtusd NUMERIC,
    deferredrev NUMERIC,
    depamor NUMERIC,
    deposits NUMERIC,
    divyield NUMERIC,
    dps NUMERIC,
    ebit NUMERIC,
    ebitda NUMERIC,
    ebitdamargin NUMERIC,
    ebitdausd NUMERIC,
    ebitusd NUMERIC,
    ebt NUMERIC,
    eps NUMERIC,
    epsdil NUMERIC,
    epsusd NUMERIC,
    equity NUMERIC,
    equityavg NUMERIC,
    equityusd NUMERIC,
    ev NUMERIC,
    evebit NUMERIC,
    evebitda NUMERIC,
    fcf NUMERIC,
    fcfps NUMERIC,
    fxusd NUMERIC,
    gp NUMERIC,
    grossmargin NUMERIC,
    intangibles NUMERIC,
    intexp NUMERIC,
    invcap NUMERIC,
    invcapavg NUMERIC,
    inventory NUMERIC,
    investments NUMERIC,
    investmentsc NUMERIC,
    investmentsnc NUMERIC,
    liabilities NUMERIC,
    liabilitiesc NUMERIC,
    liabilitiesnc NUMERIC,
    marketcap NUMERIC,
    ncf NUMERIC,
    ncfbus NUMERIC,
    ncfcommon NUMERIC,
    ncfdebt NUMERIC,
    ncfdiv NUMERIC,
    ncff NUMERIC,
    ncfi NUMERIC,
    ncfinv NUMERIC,
    ncfo NUMERIC,
    ncfx NUMERIC,
    netinc NUMERIC,
    netinccmn NUMERIC,
    netinccmnusd NUMERIC,
    netincdis NUMERIC,
    netincnci NUMERIC,
    netmargin NUMERIC,
    opex NUMERIC,
    opinc NUMERIC,
    payables NUMERIC,
    payoutratio NUMERIC,
    pb NUMERIC,
    pe NUMERIC,
    pe1 NUMERIC,
    ppnenet NUMERIC,
    prefdivis NUMERIC,
    price NUMERIC,
    ps NUMERIC,
    ps1 NUMERIC,
    receivables NUMERIC,
    retearn NUMERIC,
    revenue NUMERIC,
    revenueusd NUMERIC,
    rnd NUMERIC,
    roa NUMERIC,
    roe NUMERIC,
    roic NUMERIC,
    ros NUMERIC,
    sbcomp NUMERIC,
    sgna NUMERIC,
    sharefactor NUMERIC,
    sharesbas NUMERIC,
    shareswa NUMERIC,
    shareswadil NUMERIC,
    sps NUMERIC,
    tangibles NUMERIC,
    taxassets NUMERIC,
    taxexp NUMERIC,
    taxliabilities NUMERIC,
    tbvps NUMERIC,
    workingcapital NUMERIC,
    PRIMARY KEY (ticker, dimension, datekey, reportperiod)
);

CREATE TABLE options(
    providers_id INTEGER REFERENCES providers,
    ticker VARCHAR REFERENCES tickers(ticker),
    date TIMESTAMP,
    strike INTEGER,
    side CHARACTER(1),
    bid NUMERIC,
    ask NUMERIC,
    impvol NUMERIC,
    delta NUMERIC,
    modelprice NUMERIC,
    gamma NUMERIC,
    vega NUMERIC,
    theta NUMERIC,
    underprice NUMERIC,
    PRIMARY KEY (ticker, date)
)